In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [21]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Ayonk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9574074074074074

In [22]:
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.32407407407407407

In [23]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9666666666666667

In [24]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf


KFold(n_splits=3, random_state=None, shuffle=False)

In [25]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [26]:
def get_score(model,x_train,x_test,y_train,y__test):
    model.fit(x_train,y_train)
    return  model.score(x_test,y__test)

In [29]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)



C:\Users\Ayonk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [30]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9796296296296296

In [31]:
get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test)

0.9777777777777777

In [32]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)


In [44]:
scores_logistic = []
scores_svm = []
scores_rf = []

for train_index,test_index in kf.split(digits.data):
        x_train,x_test, y_train, y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]
        scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),  x_train,x_test, y_train, y_test))  
        scores_svm.append(get_score(SVC(gamma='auto'),  x_train,x_test, y_train, y_test))
        scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),  x_train,x_test, y_train, y_test))
        

In [45]:
scores_logistic

[0.8964941569282137, 0.9515859766277128, 0.9115191986644408]

In [46]:
scores_svm

[0.41068447412353926, 0.41569282136894825, 0.4273789649415693]

In [47]:
scores_rf

[0.9332220367278798, 0.9515859766277128, 0.9115191986644408]

In [49]:
from sklearn.model_selection import cross_val_score

In [50]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

C:\Users\Ayonk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Ayonk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [53]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [54]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

array([0.93322204, 0.95826377, 0.92821369])