In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import pickle
import joblib

In [34]:
df=pd.read_csv("homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [36]:
model=linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [38]:
model.predict([[5500]])

array([927448.63013699])

In [44]:
with open('model_pickle_name','wb') as file:
    pickle.dump(model,file)
    
with open('model_pickle_name','rb') as file:
    mp=pickle.load(file)

In [45]:
mp.predict([[5500]])

array([927448.63013699])

In [47]:
joblib.dump(model,'joblin_name')

['joblin_name']

In [50]:
mj = joblib.load('joblin_name')

In [52]:
mj.predict([[5000]])

array([859554.79452055])