In [2]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [3]:
from sklearn import datasets
iris=datasets.load_iris()

In [4]:
x=iris.data
y=iris.target

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [6]:
knn=KNeighborsClassifier(n_neighbors=1)

In [7]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=1)

In [8]:
knn.predict([[3,5,4,2]])


array([2])

In [9]:
print("Predicted target name:" ,iris['target_names'][knn.predict([[3,5,4,2]])])

Predicted target name: ['virginica']


In [10]:
x_new=np.array([[3,5,4,2]])
print("x_newshape:",x_new)

x_newshape: [[3 5 4 2]]


In [11]:
mypredict=knn.predict(x_new)

In [16]:
print("prediction",mypredict)
print("predicted target names:",iris['target_names'][mypredict])

prediction [2]
predicted target names: ['setosa' 'versicolor' 'virginica']


In [14]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [19]:
x_new=[[3,5,4,2],[5,4,3,2]]
knn.predict(x_new)


array([2, 1])

In [21]:
knn = KNeighborsClassifier(n_neighbors=3)

In [22]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=3)

In [23]:
knn.predict(x_new)

array([1, 1])

In [32]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x, y)
lr.predict(x_new)

C:\Users\Ayonk\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0])