In [6]:
import numpy as np
x,y=np.arange(10).reshape((5,2)),range(5)

In [7]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
y

range(0, 5)

In [9]:
list(y)

[0, 1, 2, 3, 4]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=4)

In [14]:
x_train

array([[2, 3],
       [8, 9],
       [4, 5]])

In [15]:
x_test

array([[0, 1],
       [6, 7]])

In [16]:
y_test

[0, 3]

In [17]:
y_train

[1, 4, 2]

In [18]:
train_test_split(y,shuffle=False)

[[0, 1, 2], [3, 4]]

In [21]:
from sklearn.datasets import load_iris
iris=load_iris()
x=iris.data
y=iris.target
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [24]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0)

In [25]:
print(x_train.shape)
print(x_test.shape)

(112, 4)
(38, 4)


In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=4)

In [27]:
print(x_test.shape)
print(y_test.shape)

(60, 4)
(60,)


In [29]:
# আগের মতো KNeighborsClassifier ইমপোর্ট করি 
from sklearn.neighbors import KNeighborsClassifier
# মডেলকে ইনস্ট্যানশিয়েট করলাম 
# যদি "কে-নিয়ারেস্ট নেইবার্স" ক্লাসিফায়ারের নেইবার ৩ হয়
knn = KNeighborsClassifier(n_neighbors=3)
# মডেলের মধ্যে সম্পৰ্ক তৈরি করি X_train এবং y_train দিয়ে
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [30]:
# প্রেডিকশন করছি টেস্ট সেট ধরে 
y_pred = knn.predict(x_test)
# প্রেডিক্টেড রেসপন্স ভ্যালুর (y_pred) সাথে তুলনা করছি 
# আসল রেসপন্স ভ্যালু (y_test)কে 
# আগের মতো ইমপোর্ট করলাম metricsকে 
from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667


In [32]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train, y_train)
y_pred = knn.predict(x_test)
print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667
