In [23]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [3]:
mnist=tf.keras.datasets.mnist

In [6]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test=x_train/255,x_test/255

In [9]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(.2),
    tf.keras.layers.Dense(10)
])

In [10]:
predictions=model(x_train[:1]).numpy()
predictions

array([[ 0.4123501 , -0.41651735,  0.40282786,  0.24189962,  0.6343711 ,
        -0.3106357 , -0.10536538, -0.25866273,  0.13353631, -0.18369204]],
      dtype=float32)

In [11]:
tf.nn.softmax(predictions).numpy()

array([[0.13478923, 0.05884135, 0.13351183, 0.11366573, 0.16829751,
        0.06541336, 0.08031824, 0.06890298, 0.10199242, 0.07426725]],
      dtype=float32)

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [13]:
loss_fn(y_train[:1], predictions).numpy()

2.7270286

In [14]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [17]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))


Num GPUs Available:  0


In [18]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0324 - accuracy: 0.9888
Epoch 2/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0315 - accuracy: 0.9891
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0304 - accuracy: 0.9894
Epoch 4/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0293 - accuracy: 0.9902
Epoch 5/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0273 - accuracy: 0.9904
Epoch 6/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0263 - accuracy: 0.9910
Epoch 7/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0255 - accuracy: 0.9913
Epoch 8/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0233 - accuracy: 0.9921
Epoch 9/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0239 - accuracy: 0.9918
Epoch 10/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.022

In [19]:
import time
import tensorflow as tf

# Assuming you already have x_train, y_train, and a model defined
# model = ... (Your TensorFlow/Keras model)

# Record the start time
start_time = time.time()

# Train the model
model.fit(x_train, y_train, epochs=10)

# Record the end time
end_time = time.time()

# Calculate the elapsed time
elapsed_time = end_time - start_time

# Print the time taken
print(f"Training Time: {elapsed_time:.2f} seconds")


Epoch 1/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0243 - accuracy: 0.9919
Epoch 2/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0211 - accuracy: 0.9928
Epoch 3/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0195 - accuracy: 0.9932
Epoch 4/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0212 - accuracy: 0.9925
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0194 - accuracy: 0.9931
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0185 - accuracy: 0.9934
Epoch 7/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0198 - accuracy: 0.9933
Epoch 8/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0185 - accuracy: 0.9939
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0186 - accuracy: 0.9937
Epoch 10/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.018

In [20]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0900 - accuracy: 0.9812 - 754ms/epoch - 2ms/step


[0.0899609625339508, 0.9811999797821045]

In [21]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [22]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.3560053e-14, 1.5726269e-15, 4.4814907e-12, 7.0235955e-09,
        1.7398820e-16, 1.5049586e-12, 3.4946716e-31, 1.0000000e+00,
        4.6456518e-13, 5.2531574e-10],
       [3.0336859e-17, 2.3801269e-10, 1.0000000e+00, 5.1686872e-14,
        0.0000000e+00, 1.9022964e-17, 4.8813357e-15, 3.9081982e-28,
        8.0854182e-13, 0.0000000e+00],
       [3.5140144e-13, 9.9999833e-01, 5.8630284e-10, 1.6381255e-13,
        1.2233103e-07, 3.4272349e-13, 3.2900463e-10, 1.2288546e-06,
        3.1542083e-07, 5.9579625e-13],
       [1.0000000e+00, 2.0006202e-14, 9.7494263e-11, 5.4111332e-13,
        2.8865556e-12, 2.6386879e-11, 2.7248800e-11, 1.5384813e-11,
        3.0727802e-20, 3.3099497e-13],
       [1.0879368e-11, 1.9442923e-24, 5.3387579e-14, 1.5569991e-17,
        9.9998558e-01, 1.3528843e-16, 6.0935148e-15, 5.4732888e-11,
        5.8580144e-17, 1.4376772e-05]], dtype=float32)>