In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [7]:
one_hot("amazing restaurant",30)

[16, 15]

In [8]:
vocab_size=30

In [9]:
encoded_reviews= [one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[7, 2], [16, 15], [16, 21], [26, 29, 2], [29, 11, 23], [16, 2], [17, 11, 16], [20, 17], [20, 15], [20, 25]]


In [12]:
max_length=3
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding="post")
padded_reviews

array([[ 7,  2,  0],
       [16, 15,  0],
       [16, 21,  0],
       [26, 29,  2],
       [29, 11, 23],
       [16,  2,  0],
       [17, 11, 16],
       [20, 17,  0],
       [20, 15,  0],
       [20, 25,  0]])

In [18]:
embedded_vector_size=4

model=Sequential(Embedding(vocab_size,embedded_vector_size,input_length=max_length,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))



In [19]:
X=padded_reviews
y=sentiment

In [20]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              120       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________
None


In [21]:
model.fit(X, y, epochs=50, verbose=0)

In [22]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 179ms/step - loss: 0.6308 - accuracy: 0.8000


0.800000011920929

In [23]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [24]:
weights[13]

array([ 0.03976282, -0.0200871 , -0.00699196,  0.02402017], dtype=float32)

In [25]:
weights[4]

array([ 0.01486835, -0.00092769, -0.02654796,  0.02345142], dtype=float32)

In [26]:
weights[16]

array([ 0.07456431, -0.04702202,  0.09683806,  0.0688447 ], dtype=float32)